# Wx::SF::TextShape - control shape class
# Copyright (c) M.J.N. Corino, The Netherlands

require 'wx/shapes/shapes/rect_shape'

module Wx::SF

  # Class encapsulates a special shape able to manage assigned GUI controls (widgets). The GUI control's
  # position and size can by modified via parent control shape. User can also specify how events incoming from the
  # managed GUI control are processed.
  #
  # Note that the managed controls use a shape canvas as their parent window so these shapes cannot be used
  # without existing and properly initialized shape canvas. Moreover, managed GUI controls are not serialized in any
  # way internally so it is completely up to the user to provide this functionality if needed.
  class ControlShape < RectShape

    # Auxiliary class used by Wx::SF::ControlShape. All events generated by a GUI control (widget)
    # managed by parent control shape are redirected to this event sink which invokes a default event handler
    # or send a copy of the event to shape canvas if requested.
    class EventSink < Wx::EvtHandler

    end

    # @overload initialize()
    #   Default constructor.
    # @overload initialize(pos, size, diagram)
    #   User constructor.
    #   @param [Wx::Point] pos Initial position
    #   @param [Wx::Size] size Initial size
    #   @param [Wx::SF::Diagram] diagram parent diagram
    def initialize(*args)

    end

  end

end
