# Simple workflow for deploying static content to GitHub Pages
name: Deploy wx/shapes Pages

on:
  push:
    tags:
      - v*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup Ruby gems
        run: |
          bundle config set --local with documentation
          bundle config set --local without wxruby
          bundle install

      - name: Build wxRuby3Shapes HTML docs
        run: |
          bundle exec yardoc

      - name: Copy assets into HTML output folder
        run: |
          cp -r assets rdoc

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload Yard output only
          path: 'rdoc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
